//**********************************************************************
//ÎÄ¼þÃû:sys_para.h
//**********************************************************************
#ifndef _SYS_PARA_H
#define _SYS_PARA_H
#include "type_def.h"
void Change_Asph_Alm_Set(void);
uint8 Get_Asph_Alm_Set(void);
uint8 Wr_Asph_EEPROM(void);
uint8 Rd_Asph_EEPROM(void);
void Reset_Alm_Silence_T(uint8 type);
uint8 Get_Alm_Silence_T(void);
uint8 Save_Rate_Usr_Set(void);
uint8 Rd_Rate_Usr_Set_EEP(void);
uint8 Inc_Dec_Rate_Usr_Set(uint8 dir,uint8 step);
sint32 Get_Rate_Usr_Set(void);
uint8 Check_Rate_Usr_Set(void);
uint8 Get_IE_Usr_Set(void);
uint8 Inc_Dec_IE_Usr_Set(uint8 dir,uint8 step);
uint8 Check_IE_Usr_Set(void);
uint8 Save_IE_Usr_Set(void);
uint8 Rd_IE_Usr_Set_EEP(void);
sint16 Get_Pl_Usr_Set(void);
uint8 Inc_Dec_Pl_Usr_Set(uint8 dir,uint8 step);
uint8 Check_Pl_Usr_Set(void);
uint8 Save_Pl_Usr_Set(void);
uint8 Rd_Pl_Usr_Set_EEP(void);
uint8 Get_Asph_Usr_Set(void);
uint8 Inc_Dec_Asph_Usr_Set(uint8 dir,uint8 step);
uint8 Check_Asph_Usr_Set(void);
uint8 Save_Asph_Usr_Set(void);
uint8 Rd_Asph_Usr_Set_EEP(void);
uint8 Get_Scr_Bri(void);
uint8 Inc_Dec_Scr_Bri(uint8 dir,uint8 step);
uint8 Check_Scr_Bri(void);
uint8 Save_Scr_Bri(void);
uint8 Rd_Scr_BRi_EEP(void);
uint8 Get_Alm_Vol(void);
uint8 Inc_Dec_Alm_Vol(uint8 dir,uint8 step);
uint8 Check_Alm_Vol(void);
uint8 Save_Alm_Vol(void);
uint8 Rd_Alm_Vol_EEP(void);
uint8 Get_All_Ch(void);
uint8 Change_All_Ch_Set(void);
uint8 Save_All_Ch_Set(void);
uint8 Rd_All_Ch_Set_EEP(void);
uint8 Get_Br_Mode_Sel(void);
void Set_Br_Mode_Sel(uint8 para);
uint8 Save_Br_Mode_Sel(void);
uint8 Rd_Br_M_Sel_EEP(void);
uint8 Get_O2_Alm_L(void);
uint8 Inc_Dec_O2_Alm_L(uint8 dir,uint8 step);
uint8 Check_O2_Alm_L(void);
uint8 Save_O2_Alm_L(void);
uint8 Rd_O2_Alm_L_EEP(void);
uint8 Get_O2_Alm_H(void);
uint8 Inc_Dec_O2_Alm_H(uint8 dir,uint8 step);
uint8 Check_O2_Alm_H(void);
uint8 Save_O2_Alm_H(void);
uint8 Rd_O2_Alm_H_EEP(void);
sint32 Get_VE_Alm_L(void);
uint8 Inc_Dec_Ve_Alm_L(uint8 dir,uint8 step);
uint8 Check_Ve_Alm_L(void);
uint8 Save_Ve_Alm_L(void);
uint8 Rd_Ve_Alm_L_EEP(void);
sint32 Get_VE_Alm_H(void);
uint8 Inc_Dec_Ve_Alm_H(uint8 dir,uint8 step);
uint8 Check_Ve_Alm_H(void);
uint8 Save_Ve_Alm_H(void);
uint8 Rd_Ve_Alm_H_EEP(void);
sint16 Get_Vt_Alm_L(void);
uint8 Inc_Dec_Vt_Alm_L(uint8 dir,uint8 step);
uint8 Check_Vt_Alm_L(void);
uint8 Save_Vt_Alm_L(void);
uint8 Rd_Vt_Alm_L_EEP(void);
sint16 Get_Vt_Alm_H(void);
uint8 Inc_Dec_Vt_Alm_H(uint8 dir,uint8 step);
uint8 Check_Vt_Alm_H(void);
uint8 Save_Vt_Alm_H(void);
uint8 Rd_Vt_Alm_H_EEP(void);
uint8 Get_Vt_Alm_Switch(void);
void Change_Vt_Alm_Switch(void);
sint16 Get_Alt(void);
uint8 Inc_Dec_Alt(uint8 dir,uint8 step);
uint8 Check_Alt(void);
uint8 Save_Alt(void);
uint8 Rd_Alt_EEP(void);
uint8 Get_Drv_Gas(void);
void Set_Drv_Gas(uint8 para);
uint8 Save_Drv_Gas(void);
uint8 Rd_Drv_Gas_EEP(void);
uint8 Get_O2_Inspect(void);
void Set_O2_Inspect(uint8 para);
uint8 Save_O2_Inspect(void);
uint8 Rd_O2_Inspect_EEP(void);
uint8 Get_Alm_Mess_D(void);
void Set_Alm_Mess_D(uint8 para);
uint8 Save_Alm_Mess_D(void);
uint8 Rd_Alm_Mess_D_EEP(void);
sint32 Get_Pmax(void);
uint8 Get_Pmax_Units(void);
uint8 Set_Pmax(sint32 p,uint8 units);
sint32 Get_Pavr(void);
uint8 Get_Pavr_Units(void);
uint8 Set_Pavr(sint32 p,uint8 units);
sint32 Get_Paw(void);
uint8 Get_Paw_Units(void);
uint8 Set_Paw(sint32 p,uint8 units);
sint32 Get_Pmin(void);
uint8 Get_Pmin_Units(void);
uint8 Set_Pmin(sint32 p,uint8 units);
sint32 Get_Vt(void);
uint8 Get_Vt_Units(void);
uint8 Set_Vt(sint32 p,uint8 units);
sint32 Get_Rate_Meas(void);
uint8 Set_Rate_Meas(sint32 p);
sint32 Get_Ve(void);
uint8 Get_Ve_Units(void);
uint8 Set_Ve(sint32 p,uint8 units);
sint32 Get_O2(void);
uint8 Get_O2_Units(void);
uint8 Set_O2(sint32 p,uint8 units);
sint32 Get_Humor(void);
uint8 Get_Humor_Units(void);
uint8 Set_Humor(sint32 p,uint8 units);
sint32 Get_Batt_Vol(void);
void Log_Batt_Vol(sint32 vol);
sint32 Get_Batt_Charge_I(void);
void Log_Batt_Charge_I(sint32 i);
uint8 Get_Key_Sound_Switch(void);
void Set_Key_Sound_Switch(uint8 para);
uint8 Save_Key_Sound_Switch(void);
uint8 Rd_Key_Sound_Switch_EEP(void);
uint8 Get_Vt_Filter_Const(void);
uint8 Inc_Dec_Vt_Filt_C(uint8 dir,uint8 step);
uint8 Check_Vte_Filt_C(void);
uint8 Save_Vt_Filt_C(void);
uint8 Rd_Vt_Filt_C_EEP(void);
uint8 Get_O2_Flash_Cyc(void);
uint8 Inc_Dec_O2_Flash_Cyc(uint8 dir,uint8 step);
uint8 Check_O2_Flash_Cyc(void);
uint8 Save_O2_Flash_Cyc(void);
uint8 Rd_O2_Flash_Cyc_EEP(void);
sint16 Get_Pl_Comp(void);
uint8 Inc_Dec_Pl_Comp(uint8 dir,uint8 step);
uint8 Check_Pl_Comp(void);
uint8 Save_Pl_Comp(void);
uint8 Rd_Pl_Comp_EEP(void);
sint32 Get_Paw_No_Raise(void);
uint8 Inc_Dec_Paw_No_R(uint8 dir,uint8 step);
uint8 Check_Paw_No_R(void);
uint8 Save_Paw_No_R(void);
uint8 Rd_Paw_No_R_EEP(void);
uint8 Get_P_Trig_Usr_Set(void);
uint8 Inc_Dec_P_Trig_Usr_Set(uint8 dir,uint8 step);
uint8 Check_P_Trig_Usr_Set(void);
uint8 Save_P_Trig_Usr_Set(void);
uint8 Rd_P_Trig_Usr_Set_EEP(void);
uint8 Get_Trig_Win_Usr_Set(void);
uint8 Inc_Dec_Trig_Win_Usr_Set(uint8 dir,uint8 step);
uint8 Check_Trig_Win_Usr_Set(void);
uint8 Save_Trig_Win_Usr_Set(void);
uint8 Rd_Trig_Win_Usr_Set_EEP(void);
#endif